name = "api"
main = "src/index.ts"
compatibility_date = "2025-12-25"

# ── Production ──
kv_namespaces = [
  { binding = "DEAD_DROP", id = "35daf343d0244b989e423bf1bc0baf5e" }
]

# ── Local Dev (wrangler dev) ──
[env.dev]
kv_namespaces = [
  { binding = "DEAD_DROP", id = "35daf343d0244b989e423bf1bc0baf5e", preview_id = "local-dev-preview" }
]
